### ISSUE TITLE
Game crash when injecting

### ISSUE THREAD

**Issue by Knoxyzz** [CodeRedModding/CodeRed-Launcher#1]
As soon as the text goes zo injected succesful changed where made to the game the game crashes.

**Comment by Knoxyzz** [comment]
[crash_logs_1672357121.zip](https://github.com/CodeRedModding/CodeRed-Launcher/files/10322531/crash_logs_1672357121.zip)

**Comment by ItsBranK** [comment]
Please only create issues related to the launcher on this repo.
